sudo: false
language: python
python:
- '3.4'
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texinfo
    - mercurial
install:
- pip install sphinx
- pip install sphinx_bootstrap_theme
script:
- GH_USER=LoyolaChicagoCS GH_REPO=coursedescriptions "./gh-pages.sh"
env:
  global:
  - secure: Wt8lqr0vx4nAyTlUPqdOZfDxuZ10IVyo1o2KL/JOkn4+mIxR5AoieN7xyImK5qhMKPy8fNxowz6CkMypCGNVT26kpnLJYXYF2lZf8H/6teYZTDMPLcj+A46rkBxYALtQrgpEbC4j6BI6Sk78LrLBs8+VC+MjpGB2/zq0qBi2FKc=
